source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'PLMediaStreamingKitDemo' do
  pod 'PLMediaStreamingKit', '~> 3.1.1'
  pod 'Masonry'
  pod 'BlocksKit'

  pod 'SVProgressHUD'
  pod 'FURenderKit_nama', '~> 8.13.0'
  
end
